steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nintendo-scraper', '.']
images:
  - 'gcr.io/$PROJECT_ID/nintendo-scraper'
options:
  logging: CLOUD_LOGGING_ONLY
